dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0"
dotenv: .env
networks:
  default: development
  rinkeby:
    price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify_api: True
  development:
    verify_api: False
  ganache-local:
    verify_api: False
  mainnet-fork-dev:
    price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify_api: False
#   mainnet-fork-dev:
#     eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
#     verify: False

# wallets:
#   from_key: ${PRIVATE_KEY}